### PR TITLE
Annotated CharBuffer.java and removed all errors in ParsePosition.java, ThreadGroup.java and CharBuffer.java

### PR DESCRIPTION
**Pull request by Kakarot-SSJ4**
jdk8.jar was built from https://github.com/Kakarot-SSJ4/checker-framework/tree/annotate-new

### CODE REVIEW

**Comment by Kakarot-SSJ4** [comment]
@kelloggm @panacekcz

**Comment by wmdietl** [comment]
We recently updated https://github.com/typetools/annotated-libraries/blob/master/README.md
Can you please start following the suggestion to include fork and branch information in commits?
That will make it easier to reproduce what sources were used to build something. A link in the PR description is also a good idea.

**Comment by Kakarot-SSJ4** [comment]
@kelloggm @panacekcz

**Comment by Kakarot-SSJ4** [comment]
@kelloggm @panacekcz

**Comment by Kakarot-SSJ4** [comment]
@kelloggm @panacekcz

**Pull request merged**
